// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsnaxwdzppveneedmwkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzbmF4d2R6cHB2ZW5lZWRtd2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzI1NTUsImV4cCI6MjA2OTEwODU1NX0.BqcNA7F850MAIRdhRYSp_LSEjLCudi-711ZhEDODS_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});